"""
Unit tests for services.strategy_synthesis — the core payoff/objective/
search math only. No network or broker dependency: `service.py` (the live
option-chain adapter) is intentionally not exercised here since it just
wires this pure core to `option_chain_service`, which has its own tests.
"""

import math

import numpy as np
import pytest

from services.strategy_synthesis import (
    LegCandidate,
    SynthesizedLeg,
    combo_payoff,
    evaluate_risk,
    synthesize,
)
from services.strategy_synthesis.objective import score_combo

LOT_SIZE = 1


def test_combo_payoff_bull_call_spread_shape():
    prices = np.array([80.0, 100.0, 110.0, 120.0, 140.0])
    legs = [
        SynthesizedLeg(strike=100, option_type="CE", side="BUY", premium=5),
        SynthesizedLeg(strike=120, option_type="CE", side="SELL", premium=2),
    ]
    payoff = combo_payoff(prices, legs, LOT_SIZE)

    assert payoff[0] == pytest.approx(-3.0)  # below both strikes: net premium paid, flat
    assert payoff[2] == pytest.approx((110 - 100) - 3.0)  # between strikes: rises 1:1
    assert payoff[3] == pytest.approx(20 - 3.0)  # at/above short strike: capped
    assert payoff[4] == pytest.approx(20 - 3.0)


def test_evaluate_risk_bounded_spread():
    prices = np.linspace(80, 140, 61)
    legs = [
        SynthesizedLeg(strike=100, option_type="CE", side="BUY", premium=5),
        SynthesizedLeg(strike=120, option_type="CE", side="SELL", premium=2),
    ]
    payoff = combo_payoff(prices, legs, LOT_SIZE)
    risk = evaluate_risk(prices, payoff)

    assert risk.max_profit == pytest.approx(17.0, abs=0.5)
    assert risk.max_loss == pytest.approx(-3.0, abs=0.5)
    assert math.isfinite(risk.max_profit)
    assert math.isfinite(risk.max_loss)
    assert len(risk.breakevens) == 1
    assert risk.breakevens[0] == pytest.approx(103.0, abs=1.0)


def test_evaluate_risk_unbounded_naked_short_call():
    prices = np.linspace(80, 140, 61)
    legs = [SynthesizedLeg(strike=100, option_type="CE", side="SELL", premium=5)]
    payoff = combo_payoff(prices, legs, LOT_SIZE)
    risk = evaluate_risk(prices, payoff)

    assert risk.max_profit == pytest.approx(5.0)
    assert risk.max_loss == -math.inf
    assert risk.profit_loss_ratio == 0.0


def test_evaluate_risk_unbounded_naked_long_call():
    prices = np.linspace(80, 140, 61)
    legs = [SynthesizedLeg(strike=100, option_type="CE", side="BUY", premium=5)]
    payoff = combo_payoff(prices, legs, LOT_SIZE)
    risk = evaluate_risk(prices, payoff)

    assert risk.max_profit == math.inf
    assert risk.max_loss == pytest.approx(-5.0)
    assert risk.profit_loss_ratio == 50.0


def test_shape_score_perfect_match_scores_near_one():
    prices = np.linspace(80, 140, 61)
    legs = [
        SynthesizedLeg(strike=100, option_type="CE", side="BUY", premium=5),
        SynthesizedLeg(strike=120, option_type="CE", side="SELL", premium=2),
    ]
    payoff = combo_payoff(prices, legs, LOT_SIZE)

    scored = score_combo(prices, payoff, legs, LOT_SIZE, shape_weight=1.0, risk_weight=0.0)

    assert scored.shape_score > 0.99


def test_shape_score_mirror_image_scores_zero():
    prices = np.linspace(80, 140, 61)
    legs = [
        SynthesizedLeg(strike=100, option_type="CE", side="BUY", premium=5),
        SynthesizedLeg(strike=120, option_type="CE", side="SELL", premium=2),
    ]
    payoff = combo_payoff(prices, legs, LOT_SIZE)
    inverted_target = -payoff  # a loss-shaped curve where the real payoff is a profit hump

    scored = score_combo(prices, inverted_target, legs, LOT_SIZE, shape_weight=1.0, risk_weight=0.0)

    assert scored.shape_score == 0.0


def test_synthesize_recovers_known_bull_call_spread():
    # Candidate pool contains the exact legs of a bull call spread plus
    # several distractor strikes; the target curve is generated by that
    # exact spread. The search should recover those same two legs.
    candidates = [
        LegCandidate(strike=k, option_type=t, premium=p)
        for k, p in [(90, 12), (95, 9), (100, 6), (105, 4), (110, 2.5), (115, 1.5), (120, 1)]
        for t in ("CE", "PE")
    ]
    true_legs = [
        SynthesizedLeg(strike=100, option_type="CE", side="BUY", premium=6),
        SynthesizedLeg(strike=115, option_type="CE", side="SELL", premium=1.5),
    ]
    prices = np.linspace(80, 140, 121)
    target_payoff = combo_payoff(prices, true_legs, LOT_SIZE)
    target_points = list(zip(prices.tolist(), target_payoff.tolist(), strict=True))

    results = synthesize(
        target_points=target_points,
        candidates=candidates,
        max_legs=2,
        min_legs=2,
        lot_size=LOT_SIZE,
        top_n=3,
    )

    assert results
    top = results[0]
    found = {(leg.strike, leg.option_type, leg.side) for leg in top.legs}
    expected = {(100, "CE", "BUY"), (115, "CE", "SELL")}
    assert found == expected
    assert top.shape_score > 0.98


def test_synthesize_respects_max_legs():
    candidates = [
        LegCandidate(strike=k, option_type=t, premium=5) for k in (90, 95, 100, 105, 110) for t in ("CE", "PE")
    ]
    target_points = [(80.0, -3.0), (100.0, -3.0), (110.0, 7.0), (140.0, 7.0)]

    results = synthesize(target_points=target_points, candidates=candidates, max_legs=2, top_n=5)

    assert results
    assert all(len(r.legs) <= 2 for r in results)


def test_synthesize_empty_inputs_return_empty():
    assert synthesize(target_points=[], candidates=[LegCandidate(100, "CE", 5)], max_legs=2) == []
    assert synthesize(target_points=[(100.0, 0.0)], candidates=[], max_legs=2) == []


def test_synthesize_invalid_weights_raise():
    candidates = [LegCandidate(100, "CE", 5)]
    target_points = [(90.0, 0.0), (110.0, 0.0)]
    with pytest.raises(ValueError):
        synthesize(target_points=target_points, candidates=candidates, max_legs=1, shape_weight=0.0)
    with pytest.raises(ValueError):
        synthesize(target_points=target_points, candidates=candidates, max_legs=1, risk_weight=-0.1)


def test_synthesize_falls_back_to_greedy_for_large_candidate_pools():
    # 40 strikes x 2 types x 2 sides = 160 templates; choosing 4 is
    # ~52M combinations, well above the exhaustive-search cap, so this
    # exercises the greedy + local-search path instead.
    candidates = [
        LegCandidate(strike=float(k), option_type=t, premium=max(0.5, 20 - abs(k - 100) * 0.3))
        for k in range(60, 140, 2)
        for t in ("CE", "PE")
    ]
    target_points = [(60.0, -5.0), (100.0, -5.0), (110.0, 15.0), (140.0, 15.0)]

    results = synthesize(target_points=target_points, candidates=candidates, max_legs=4, top_n=3)

    assert results
    assert all(1 <= len(r.legs) <= 4 for r in results)
    assert all(math.isfinite(r.risk.max_loss) or r.risk.max_loss == -math.inf for r in results)
