"""
Unit tests for services.strategy_synthesis — the core payoff/objective/
search math only. No network or broker dependency: `service.py` (the live
option-chain adapter) is intentionally not exercised here since it just
wires this pure core to `option_chain_service`, which has its own tests.
"""

import math

import numpy as np
import pytest

from services.strategy_synthesis import (
    LegCandidate,
    SynthesizedLeg,
    combo_payoff,
    evaluate_risk,
    synthesize,
    win_probability,
)
from services.strategy_synthesis.objective import score_combo

LOT_SIZE = 1


def test_combo_payoff_bull_call_spread_shape():
    prices = np.array([80.0, 100.0, 110.0, 120.0, 140.0])
    legs = [
        SynthesizedLeg(strike=100, option_type="CE", side="BUY", premium=5),
        SynthesizedLeg(strike=120, option_type="CE", side="SELL", premium=2),
    ]
    payoff = combo_payoff(prices, legs, LOT_SIZE)

    assert payoff[0] == pytest.approx(-3.0)  # below both strikes: net premium paid, flat
    assert payoff[2] == pytest.approx((110 - 100) - 3.0)  # between strikes: rises 1:1
    assert payoff[3] == pytest.approx(20 - 3.0)  # at/above short strike: capped
    assert payoff[4] == pytest.approx(20 - 3.0)


def test_evaluate_risk_bounded_spread():
    prices = np.linspace(80, 140, 61)
    legs = [
        SynthesizedLeg(strike=100, option_type="CE", side="BUY", premium=5),
        SynthesizedLeg(strike=120, option_type="CE", side="SELL", premium=2),
    ]
    payoff = combo_payoff(prices, legs, LOT_SIZE)
    risk = evaluate_risk(prices, payoff)

    assert risk.max_profit == pytest.approx(17.0, abs=0.5)
    assert risk.max_loss == pytest.approx(-3.0, abs=0.5)
    assert math.isfinite(risk.max_profit)
    assert math.isfinite(risk.max_loss)
    assert len(risk.breakevens) == 1
    assert risk.breakevens[0] == pytest.approx(103.0, abs=1.0)


def test_evaluate_risk_unbounded_naked_short_call():
    prices = np.linspace(80, 140, 61)
    legs = [SynthesizedLeg(strike=100, option_type="CE", side="SELL", premium=5)]
    payoff = combo_payoff(prices, legs, LOT_SIZE)
    risk = evaluate_risk(prices, payoff)

    assert risk.max_profit == pytest.approx(5.0)
    assert risk.max_loss == -math.inf
    assert risk.profit_loss_ratio == 0.0


def test_evaluate_risk_unbounded_naked_long_call():
    prices = np.linspace(80, 140, 61)
    legs = [SynthesizedLeg(strike=100, option_type="CE", side="BUY", premium=5)]
    payoff = combo_payoff(prices, legs, LOT_SIZE)
    risk = evaluate_risk(prices, payoff)

    assert risk.max_profit == math.inf
    assert risk.max_loss == pytest.approx(-5.0)
    assert risk.profit_loss_ratio == 50.0


def test_shape_score_perfect_match_scores_near_one():
    prices = np.linspace(80, 140, 61)
    legs = [
        SynthesizedLeg(strike=100, option_type="CE", side="BUY", premium=5),
        SynthesizedLeg(strike=120, option_type="CE", side="SELL", premium=2),
    ]
    payoff = combo_payoff(prices, legs, LOT_SIZE)

    scored = score_combo(
        prices,
        payoff,
        legs,
        LOT_SIZE,
        shape_weight=1.0,
        profit_weight=0.0,
        loss_weight=0.0,
        win_prob_weight=0.0,
    )

    assert scored.shape_score > 0.99


def test_shape_score_mirror_image_scores_zero():
    prices = np.linspace(80, 140, 61)
    legs = [
        SynthesizedLeg(strike=100, option_type="CE", side="BUY", premium=5),
        SynthesizedLeg(strike=120, option_type="CE", side="SELL", premium=2),
    ]
    payoff = combo_payoff(prices, legs, LOT_SIZE)
    inverted_target = -payoff  # a loss-shaped curve where the real payoff is a profit hump

    scored = score_combo(
        prices,
        inverted_target,
        legs,
        LOT_SIZE,
        shape_weight=1.0,
        profit_weight=0.0,
        loss_weight=0.0,
        win_prob_weight=0.0,
    )

    assert scored.shape_score == 0.0


def test_synthesize_recovers_known_bull_call_spread():
    # Candidate pool contains the exact legs of a bull call spread plus
    # several distractor strikes; the target curve is generated by that
    # exact spread. With the new default weights, the search prioritizes
    # win probability + absolute max profit, so a long call (perfect
    # shape fit on the rising part, unlimited profit) would beat the
    # spread on raw score. To recover the *exact* spread as the top
    # result, this test passes a shape-dominant weighting — verifying
    # that the synthesis core can still find a known combo when the
    # caller asks for shape-first ranking.
    candidates = [
        LegCandidate(strike=k, option_type=t, premium=p)
        for k, p in [(90, 12), (95, 9), (100, 6), (105, 4), (110, 2.5), (115, 1.5), (120, 1)]
        for t in ("CE", "PE")
    ]
    true_legs = [
        SynthesizedLeg(strike=100, option_type="CE", side="BUY", premium=6),
        SynthesizedLeg(strike=115, option_type="CE", side="SELL", premium=1.5),
    ]
    prices = np.linspace(80, 140, 121)
    target_payoff = combo_payoff(prices, true_legs, LOT_SIZE)
    target_points = list(zip(prices.tolist(), target_payoff.tolist(), strict=True))

    results = synthesize(
        target_points=target_points,
        candidates=candidates,
        max_legs=2,
        min_legs=2,
        lot_size=LOT_SIZE,
        top_n=3,
        # Shape-dominant: prove the old behavior is still available.
        shape_weight=0.85,
        profit_weight=0.05,
        loss_weight=0.05,
        win_prob_weight=0.05,
    )

    assert results
    top = results[0]
    found = {(leg.strike, leg.option_type, leg.side) for leg in top.legs}
    expected = {(100, "CE", "BUY"), (115, "CE", "SELL")}
    assert found == expected
    assert top.shape_score > 0.98


def test_synthesize_respects_max_legs():
    candidates = [
        LegCandidate(strike=k, option_type=t, premium=5)
        for k in (90, 95, 100, 105, 110)
        for t in ("CE", "PE")
    ]
    target_points = [(80.0, -3.0), (100.0, -3.0), (110.0, 7.0), (140.0, 7.0)]

    results = synthesize(target_points=target_points, candidates=candidates, max_legs=2, top_n=5)

    assert results
    assert all(len(r.legs) <= 2 for r in results)


def test_synthesize_empty_inputs_return_empty():
    assert synthesize(target_points=[], candidates=[LegCandidate(100, "CE", 5)], max_legs=2) == []
    assert synthesize(target_points=[(100.0, 0.0)], candidates=[], max_legs=2) == []


def test_synthesize_invalid_weights_raise():
    candidates = [LegCandidate(100, "CE", 5)]
    target_points = [(90.0, 0.0), (110.0, 0.0)]
    # Negative weight in any of the four axes should be rejected.
    with pytest.raises(ValueError):
        synthesize(
            target_points=target_points,
            candidates=candidates,
            max_legs=1,
            profit_weight=-0.1,
        )
    with pytest.raises(ValueError):
        synthesize(
            target_points=target_points,
            candidates=candidates,
            max_legs=1,
            loss_weight=1.5,  # > 1.0 is out of range
        )
    with pytest.raises(ValueError):
        synthesize(
            target_points=target_points,
            candidates=candidates,
            max_legs=1,
            win_prob_weight=-0.1,
        )


def test_synthesize_ranks_high_profit_high_win_above_perfect_shape_low_profit():
    # User priority for the Draw Target recommendations: high win rate
    # first, then more profit, then less risk, with shape as a *gate*
    # rather than the primary axis. A near-perfect shape match on a
    # tiny-payoff spread must NOT outrank a clearly more profitable,
    # higher-win-probability combo just because the user's drawn target
    # happened to fit a low-payoff body.
    #
    # Concretely: the target is the exact payoff of a 100/115 bull
    # call spread. Under the old shape-dominant ranking, the spread
    # always won because its shape fit was ~perfect (1.0) while any
    # alternative lost on shape. Under the new ranking, a long call
    # at strike 100 has the same ~perfect shape (it's the rising part
    # of the spread) and dramatically better absolute max profit
    # (unlimited) and a comparable win probability, so it ranks first.
    candidates = [
        LegCandidate(strike=k, option_type="CE", premium=p)
        for k, p in [(90, 12), (95, 9), (100, 6), (105, 4), (110, 2.5), (115, 1.5), (120, 1)]
    ]
    prices = np.linspace(80, 140, 121)
    # Draw a flat-top target that the user *might* have intended as a
    # spread, but the ranking should be driven by the holy-grail axes
    # (win, profit, risk), not by the shape alone.
    target_points = [(80.0, 0.0), (100.0, 0.0), (115.0, 4.5), (140.0, 4.5)]

    results = synthesize(
        target_points=target_points,
        candidates=candidates,
        max_legs=2,
        min_legs=1,
        top_n=5,
        spot=100.0,
        iv=0.25,
        years=15 / 365,
    )

    assert results
    # The new priority: high profit + good shape beats a tiny-payoff
    # structure that happens to match the drawn flat-top exactly.
    # We don't pin the *exact* top result (a long call at the right
    # strike is the obvious winner; the precise strike can shift as
    # the synthesis heuristics evolve) — we assert the qualitative
    # property: the top combo has meaningful absolute max profit,
    # not the 4.5-rupee credit-spread payoff the shape alone would
    # suggest.
    top = results[0]
    if top.risk.max_profit == float("inf"):
        max_profit_finite = True
    else:
        max_profit_finite = top.risk.max_profit >= 10.0  # >> 4.5 the shape-only payoff
    assert max_profit_finite, (
        f"top result is {[(l.side, l.strike) for l in top.legs]} with max_profit="
        f"{top.risk.max_profit} — the small-payoff spread is winning on shape alone. "
        f"User explicitly asked for 'more profit, not legs that give very little'."
    )


def test_synthesize_falls_back_to_greedy_for_large_candidate_pools():
    # 40 strikes x 2 types x 2 sides = 160 templates; choosing 4 is
    # ~52M combinations, well above the exhaustive-search cap, so this
    # exercises the greedy + local-search path instead.
    candidates = [
        LegCandidate(strike=float(k), option_type=t, premium=max(0.5, 20 - abs(k - 100) * 0.3))
        for k in range(60, 140, 2)
        for t in ("CE", "PE")
    ]
    target_points = [(60.0, -5.0), (100.0, -5.0), (110.0, 15.0), (140.0, 15.0)]

    results = synthesize(target_points=target_points, candidates=candidates, max_legs=4, top_n=3)

    assert results
    assert all(1 <= len(r.legs) <= 4 for r in results)
    assert all(math.isfinite(r.risk.max_loss) or r.risk.max_loss == -math.inf for r in results)


def test_win_probability_neutral_without_market_data():
    prices = np.linspace(80, 140, 61)
    payoff = np.linspace(-5, 5, 61)  # arbitrary, irrelevant when spot/iv/years missing
    assert win_probability(prices, payoff, None, 0.2, 0.1) == 0.5
    assert win_probability(prices, payoff, 100.0, None, 0.1) == 0.5
    assert win_probability(prices, payoff, 100.0, 0.2, None) == 0.5
    assert win_probability(prices, payoff, 100.0, 0.2, 0.0) == 0.5


def test_win_probability_selling_far_otm_call_is_high():
    # A *bought* option's breakeven (strike + premium) can never land
    # meaningfully below spot — premium is always >= intrinsic value, so a
    # purchase breaks even at spot at best. High win probability instead
    # belongs to the *seller* of a far-OTM option: collects the premium and
    # keeps it unless the price makes an unlikely large move against them.
    prices = np.linspace(20, 200, 200)
    legs = [SynthesizedLeg(strike=150, option_type="CE", side="SELL", premium=1)]
    payoff = combo_payoff(prices, legs, LOT_SIZE)
    p = win_probability(prices, payoff, spot=100.0, iv=0.2, years=30 / 365)
    assert p > 0.9


def test_win_probability_deep_otm_long_call_is_low():
    # Spot 100, a call bought far OTM at strike 160 needs a large move to
    # pay off — win probability should be close to 0.
    prices = np.linspace(20, 250, 200)
    legs = [SynthesizedLeg(strike=160, option_type="CE", side="BUY", premium=1)]
    payoff = combo_payoff(prices, legs, LOT_SIZE)
    p = win_probability(prices, payoff, spot=100.0, iv=0.2, years=30 / 365)
    assert p < 0.1


def test_win_probability_is_bounded():
    prices = np.linspace(50, 150, 100)
    legs = [
        SynthesizedLeg(strike=90, option_type="CE", side="BUY", premium=8),
        SynthesizedLeg(strike=110, option_type="CE", side="SELL", premium=3),
    ]
    payoff = combo_payoff(prices, legs, LOT_SIZE)
    p = win_probability(prices, payoff, spot=100.0, iv=0.25, years=15 / 365)
    assert 0.0 <= p <= 1.0


def test_synthesize_win_prob_weight_breaks_ties_between_similar_shapes():
    # Compares a bought near-the-money call (win probability tops out
    # around 50% — see test_win_probability_selling_far_otm_call_is_high's
    # docstring for why) against a sold far-OTM call (high win probability,
    # low reward). Weighting win-probability should be reflected in each
    # result's reported figure and rank the higher-probability one first
    # when shape fit is otherwise comparable.
    candidates = [
        LegCandidate(strike=k, option_type="CE", premium=p)
        for k, p in [(70, 31), (90, 12), (95, 8), (100, 5), (150, 0.3)]
    ]
    target_points = [(60.0, -10.0), (100.0, -10.0), (110.0, 5.0), (160.0, 5.0)]

    results = synthesize(
        target_points=target_points,
        candidates=candidates,
        max_legs=1,
        min_legs=1,
        top_n=10,  # covers every single-leg combo (5 strikes x 2 sides) so both compared legs are present
        shape_weight=0.5,
        profit_weight=0.0,
        loss_weight=0.0,
        win_prob_weight=0.5,
        spot=100.0,
        iv=0.25,
        years=20 / 365,
    )

    assert results
    top = results[0]
    assert 0.0 <= top.win_probability <= 1.0
    atm_buy_result = next(r for r in results if r.legs[0].strike == 100 and r.legs[0].side == "BUY")
    otm_sell_result = next(
        r for r in results if r.legs[0].strike == 150 and r.legs[0].side == "SELL"
    )
    assert otm_sell_result.win_probability > atm_buy_result.win_probability


def test_synthesize_high_profit_combo_ranks_above_low_profit_at_similar_shape():
    # User priority: "I don't want legs which give me very less profit.
    # Want more profit." When shape fit is roughly comparable between
    # two candidates, the one with materially higher absolute max profit
    # must win — even if the smaller-profit one is a "safer" structure.
    # Here a long 95-strike call (high absolute profit, same shape fit
    # as the rising part of a 90/100 spread) outranks the 90/100 spread
    # whose capped max profit is tiny in absolute terms.
    candidates = [
        LegCandidate(strike=k, option_type="CE", premium=p)
        for k, p in [(90, 12), (95, 9), (100, 6), (105, 4), (110, 2.5), (115, 1.5), (120, 1)]
    ]
    target_points = [(80.0, 0.0), (100.0, 4.0), (140.0, 50.0)]

    results = synthesize(
        target_points=target_points,
        candidates=candidates,
        max_legs=2,
        min_legs=1,
        top_n=5,
        spot=100.0,
        iv=0.25,
        years=15 / 365,
    )

    assert results
    top = results[0]
    # The top result should have a meaningful absolute max profit, not
    # the few-rupee payoff of a tight spread.
    has_real_profit = (
        top.risk.max_profit == float("inf") or top.risk.max_profit >= 5000.0
    )
    assert has_real_profit, (
        f"top result {[(l.side, l.strike) for l in top.legs]} has max_profit="
        f"{top.risk.max_profit} — too small. User said 'I don't want legs "
        f"which give me very less profit'."
    )


def test_synthesize_default_weights_penalize_unlimited_loss_combos():
    # User priority: "low risk" matters. The new formula's loss_score
    # axis correctly penalizes a combo with unlimited max loss (a
    # naked sold call past the highest strike). A naked long call
    # (unlimited max profit, bounded max loss) outranks a naked sold
    # call (limited max profit, unlimited max loss) under the new
    # default weights, even though the sold call has a much higher
    # win probability.
    candidates = [
        LegCandidate(strike=k, option_type="CE", premium=p)
        for k, p in [(90, 12), (95, 9), (100, 6), (105, 4), (110, 2.5), (115, 1.5), (120, 1)]
    ]
    target_points = [(80.0, 0.0), (100.0, 0.0), (120.0, 5.0), (140.0, 20.0)]

    results = synthesize(
        target_points=target_points,
        candidates=candidates,
        max_legs=1,
        min_legs=1,
        top_n=10,
        spot=100.0,
        iv=0.25,
        years=15 / 365,
    )

    assert results
    # Find the naked sold call and the naked long call in the results.
    sold_call = next(
        (r for r in results if r.legs[0].side == "SELL" and r.risk.max_loss == -math.inf),
        None,
    )
    long_call = next(
        (r for r in results if r.legs[0].side == "BUY" and r.risk.max_profit == math.inf),
        None,
    )
    if sold_call and long_call:
        assert long_call.score > sold_call.score, (
            f"naked long call score={long_call.score:.3f} should beat "
            f"naked sold call score={sold_call.score:.3f} — the new "
            f"default weights must penalize unlimited max loss. "
            f"User said 'minimize risk'."
        )


def test_synthesize_profit_normalization_default_handles_tight_chains():
    # A chain with small premiums (₹1–₹10) shouldn't make every combo's
    # profit_score 0 — the adaptive normalization should scale to the
    # chain so the *best* combos in the pool score near 1.0.
    candidates = [
        LegCandidate(strike=k, option_type="CE", premium=p)
        for k, p in [(95, 1.0), (100, 2.0), (105, 1.0)]
    ]
    target_points = [(90.0, 0.0), (100.0, 0.0), (120.0, 10.0)]

    results = synthesize(
        target_points=target_points,
        candidates=candidates,
        max_legs=2,
        min_legs=1,
        top_n=3,
    )

    assert results
    # Some combo in the results has profit_score > 0 (not all 0).
    assert any(r.profit_score > 0 for r in results), (
        "all combos scored 0 on profit — the adaptive normalization is broken."
    )
